// Code generated by ent, DO NOT EDIT.

package payment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldEventTitle holds the string denoting the event_title field in the database.
	FieldEventTitle = "event_title"
	// FieldTicketQuantity holds the string denoting the ticket_quantity field in the database.
	FieldTicketQuantity = "ticket_quantity"
	// FieldTotalPrice holds the string denoting the total_price field in the database.
	FieldTotalPrice = "total_price"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldBuyerName holds the string denoting the buyer_name field in the database.
	FieldBuyerName = "buyer_name"
	// FieldBuyerEmail holds the string denoting the buyer_email field in the database.
	FieldBuyerEmail = "buyer_email"
	// FieldBuyerPhone holds the string denoting the buyer_phone field in the database.
	FieldBuyerPhone = "buyer_phone"
	// FieldPaymentKey holds the string denoting the payment_key field in the database.
	FieldPaymentKey = "payment_key"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEvent holds the string denoting the event edge name in mutations.
	EdgeEvent = "event"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the payment in the database.
	Table = "payments"
	// EventTable is the table that holds the event relation/edge.
	EventTable = "payments"
	// EventInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventInverseTable = "events"
	// EventColumn is the table column denoting the event relation/edge.
	EventColumn = "event_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "payments"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldEventID,
	FieldUserID,
	FieldEventTitle,
	FieldTicketQuantity,
	FieldTotalPrice,
	FieldCurrency,
	FieldBuyerName,
	FieldBuyerEmail,
	FieldBuyerPhone,
	FieldPaymentKey,
	FieldOrderID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTitleValidator is a validator for the "event_title" field. It is called by the builders before save.
	EventTitleValidator func(string) error
	// TicketQuantityValidator is a validator for the "ticket_quantity" field. It is called by the builders before save.
	TicketQuantityValidator func(int) error
	// TotalPriceValidator is a validator for the "total_price" field. It is called by the builders before save.
	TotalPriceValidator func(float64) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// BuyerNameValidator is a validator for the "buyer_name" field. It is called by the builders before save.
	BuyerNameValidator func(string) error
	// BuyerEmailValidator is a validator for the "buyer_email" field. It is called by the builders before save.
	BuyerEmailValidator func(string) error
	// BuyerPhoneValidator is a validator for the "buyer_phone" field. It is called by the builders before save.
	BuyerPhoneValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
	StatusCancelled Status = "cancelled"
	StatusRefunded  Status = "refunded"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusCompleted, StatusFailed, StatusCancelled, StatusRefunded:
		return nil
	default:
		return fmt.Errorf("payment: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Payment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByEventTitle orders the results by the event_title field.
func ByEventTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventTitle, opts...).ToFunc()
}

// ByTicketQuantity orders the results by the ticket_quantity field.
func ByTicketQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketQuantity, opts...).ToFunc()
}

// ByTotalPrice orders the results by the total_price field.
func ByTotalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrice, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByBuyerName orders the results by the buyer_name field.
func ByBuyerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerName, opts...).ToFunc()
}

// ByBuyerEmail orders the results by the buyer_email field.
func ByBuyerEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerEmail, opts...).ToFunc()
}

// ByBuyerPhone orders the results by the buyer_phone field.
func ByBuyerPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerPhone, opts...).ToFunc()
}

// ByPaymentKey orders the results by the payment_key field.
func ByPaymentKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentKey, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEventField orders the results by event field.
func ByEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
