// Code generated by ent, DO NOT EDIT.

package payment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldEventID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUserID, v))
}

// EventTitle applies equality check predicate on the "event_title" field. It's identical to EventTitleEQ.
func EventTitle(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldEventTitle, v))
}

// TicketQuantity applies equality check predicate on the "ticket_quantity" field. It's identical to TicketQuantityEQ.
func TicketQuantity(v int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldTicketQuantity, v))
}

// TotalPrice applies equality check predicate on the "total_price" field. It's identical to TotalPriceEQ.
func TotalPrice(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldTotalPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCurrency, v))
}

// BuyerName applies equality check predicate on the "buyer_name" field. It's identical to BuyerNameEQ.
func BuyerName(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerEmail applies equality check predicate on the "buyer_email" field. It's identical to BuyerEmailEQ.
func BuyerEmail(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldBuyerEmail, v))
}

// BuyerPhone applies equality check predicate on the "buyer_phone" field. It's identical to BuyerPhoneEQ.
func BuyerPhone(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldBuyerPhone, v))
}

// PaymentKey applies equality check predicate on the "payment_key" field. It's identical to PaymentKeyEQ.
func PaymentKey(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldPaymentKey, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldOrderID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUpdatedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldEventID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldUserID))
}

// EventTitleEQ applies the EQ predicate on the "event_title" field.
func EventTitleEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldEventTitle, v))
}

// EventTitleNEQ applies the NEQ predicate on the "event_title" field.
func EventTitleNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldEventTitle, v))
}

// EventTitleIn applies the In predicate on the "event_title" field.
func EventTitleIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldEventTitle, vs...))
}

// EventTitleNotIn applies the NotIn predicate on the "event_title" field.
func EventTitleNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldEventTitle, vs...))
}

// EventTitleGT applies the GT predicate on the "event_title" field.
func EventTitleGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldEventTitle, v))
}

// EventTitleGTE applies the GTE predicate on the "event_title" field.
func EventTitleGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldEventTitle, v))
}

// EventTitleLT applies the LT predicate on the "event_title" field.
func EventTitleLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldEventTitle, v))
}

// EventTitleLTE applies the LTE predicate on the "event_title" field.
func EventTitleLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldEventTitle, v))
}

// EventTitleContains applies the Contains predicate on the "event_title" field.
func EventTitleContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldEventTitle, v))
}

// EventTitleHasPrefix applies the HasPrefix predicate on the "event_title" field.
func EventTitleHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldEventTitle, v))
}

// EventTitleHasSuffix applies the HasSuffix predicate on the "event_title" field.
func EventTitleHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldEventTitle, v))
}

// EventTitleEqualFold applies the EqualFold predicate on the "event_title" field.
func EventTitleEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldEventTitle, v))
}

// EventTitleContainsFold applies the ContainsFold predicate on the "event_title" field.
func EventTitleContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldEventTitle, v))
}

// TicketQuantityEQ applies the EQ predicate on the "ticket_quantity" field.
func TicketQuantityEQ(v int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldTicketQuantity, v))
}

// TicketQuantityNEQ applies the NEQ predicate on the "ticket_quantity" field.
func TicketQuantityNEQ(v int) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldTicketQuantity, v))
}

// TicketQuantityIn applies the In predicate on the "ticket_quantity" field.
func TicketQuantityIn(vs ...int) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldTicketQuantity, vs...))
}

// TicketQuantityNotIn applies the NotIn predicate on the "ticket_quantity" field.
func TicketQuantityNotIn(vs ...int) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldTicketQuantity, vs...))
}

// TicketQuantityGT applies the GT predicate on the "ticket_quantity" field.
func TicketQuantityGT(v int) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldTicketQuantity, v))
}

// TicketQuantityGTE applies the GTE predicate on the "ticket_quantity" field.
func TicketQuantityGTE(v int) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldTicketQuantity, v))
}

// TicketQuantityLT applies the LT predicate on the "ticket_quantity" field.
func TicketQuantityLT(v int) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldTicketQuantity, v))
}

// TicketQuantityLTE applies the LTE predicate on the "ticket_quantity" field.
func TicketQuantityLTE(v int) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldTicketQuantity, v))
}

// TotalPriceEQ applies the EQ predicate on the "total_price" field.
func TotalPriceEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldTotalPrice, v))
}

// TotalPriceNEQ applies the NEQ predicate on the "total_price" field.
func TotalPriceNEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldTotalPrice, v))
}

// TotalPriceIn applies the In predicate on the "total_price" field.
func TotalPriceIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldTotalPrice, vs...))
}

// TotalPriceNotIn applies the NotIn predicate on the "total_price" field.
func TotalPriceNotIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldTotalPrice, vs...))
}

// TotalPriceGT applies the GT predicate on the "total_price" field.
func TotalPriceGT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldTotalPrice, v))
}

// TotalPriceGTE applies the GTE predicate on the "total_price" field.
func TotalPriceGTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldTotalPrice, v))
}

// TotalPriceLT applies the LT predicate on the "total_price" field.
func TotalPriceLT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldTotalPrice, v))
}

// TotalPriceLTE applies the LTE predicate on the "total_price" field.
func TotalPriceLTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldTotalPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldCurrency, v))
}

// BuyerNameEQ applies the EQ predicate on the "buyer_name" field.
func BuyerNameEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerNameNEQ applies the NEQ predicate on the "buyer_name" field.
func BuyerNameNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldBuyerName, v))
}

// BuyerNameIn applies the In predicate on the "buyer_name" field.
func BuyerNameIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldBuyerName, vs...))
}

// BuyerNameNotIn applies the NotIn predicate on the "buyer_name" field.
func BuyerNameNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldBuyerName, vs...))
}

// BuyerNameGT applies the GT predicate on the "buyer_name" field.
func BuyerNameGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldBuyerName, v))
}

// BuyerNameGTE applies the GTE predicate on the "buyer_name" field.
func BuyerNameGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldBuyerName, v))
}

// BuyerNameLT applies the LT predicate on the "buyer_name" field.
func BuyerNameLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldBuyerName, v))
}

// BuyerNameLTE applies the LTE predicate on the "buyer_name" field.
func BuyerNameLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldBuyerName, v))
}

// BuyerNameContains applies the Contains predicate on the "buyer_name" field.
func BuyerNameContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldBuyerName, v))
}

// BuyerNameHasPrefix applies the HasPrefix predicate on the "buyer_name" field.
func BuyerNameHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldBuyerName, v))
}

// BuyerNameHasSuffix applies the HasSuffix predicate on the "buyer_name" field.
func BuyerNameHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldBuyerName, v))
}

// BuyerNameEqualFold applies the EqualFold predicate on the "buyer_name" field.
func BuyerNameEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldBuyerName, v))
}

// BuyerNameContainsFold applies the ContainsFold predicate on the "buyer_name" field.
func BuyerNameContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldBuyerName, v))
}

// BuyerEmailEQ applies the EQ predicate on the "buyer_email" field.
func BuyerEmailEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldBuyerEmail, v))
}

// BuyerEmailNEQ applies the NEQ predicate on the "buyer_email" field.
func BuyerEmailNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldBuyerEmail, v))
}

// BuyerEmailIn applies the In predicate on the "buyer_email" field.
func BuyerEmailIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldBuyerEmail, vs...))
}

// BuyerEmailNotIn applies the NotIn predicate on the "buyer_email" field.
func BuyerEmailNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldBuyerEmail, vs...))
}

// BuyerEmailGT applies the GT predicate on the "buyer_email" field.
func BuyerEmailGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldBuyerEmail, v))
}

// BuyerEmailGTE applies the GTE predicate on the "buyer_email" field.
func BuyerEmailGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldBuyerEmail, v))
}

// BuyerEmailLT applies the LT predicate on the "buyer_email" field.
func BuyerEmailLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldBuyerEmail, v))
}

// BuyerEmailLTE applies the LTE predicate on the "buyer_email" field.
func BuyerEmailLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldBuyerEmail, v))
}

// BuyerEmailContains applies the Contains predicate on the "buyer_email" field.
func BuyerEmailContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldBuyerEmail, v))
}

// BuyerEmailHasPrefix applies the HasPrefix predicate on the "buyer_email" field.
func BuyerEmailHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldBuyerEmail, v))
}

// BuyerEmailHasSuffix applies the HasSuffix predicate on the "buyer_email" field.
func BuyerEmailHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldBuyerEmail, v))
}

// BuyerEmailEqualFold applies the EqualFold predicate on the "buyer_email" field.
func BuyerEmailEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldBuyerEmail, v))
}

// BuyerEmailContainsFold applies the ContainsFold predicate on the "buyer_email" field.
func BuyerEmailContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldBuyerEmail, v))
}

// BuyerPhoneEQ applies the EQ predicate on the "buyer_phone" field.
func BuyerPhoneEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldBuyerPhone, v))
}

// BuyerPhoneNEQ applies the NEQ predicate on the "buyer_phone" field.
func BuyerPhoneNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldBuyerPhone, v))
}

// BuyerPhoneIn applies the In predicate on the "buyer_phone" field.
func BuyerPhoneIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldBuyerPhone, vs...))
}

// BuyerPhoneNotIn applies the NotIn predicate on the "buyer_phone" field.
func BuyerPhoneNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldBuyerPhone, vs...))
}

// BuyerPhoneGT applies the GT predicate on the "buyer_phone" field.
func BuyerPhoneGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldBuyerPhone, v))
}

// BuyerPhoneGTE applies the GTE predicate on the "buyer_phone" field.
func BuyerPhoneGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldBuyerPhone, v))
}

// BuyerPhoneLT applies the LT predicate on the "buyer_phone" field.
func BuyerPhoneLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldBuyerPhone, v))
}

// BuyerPhoneLTE applies the LTE predicate on the "buyer_phone" field.
func BuyerPhoneLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldBuyerPhone, v))
}

// BuyerPhoneContains applies the Contains predicate on the "buyer_phone" field.
func BuyerPhoneContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldBuyerPhone, v))
}

// BuyerPhoneHasPrefix applies the HasPrefix predicate on the "buyer_phone" field.
func BuyerPhoneHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldBuyerPhone, v))
}

// BuyerPhoneHasSuffix applies the HasSuffix predicate on the "buyer_phone" field.
func BuyerPhoneHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldBuyerPhone, v))
}

// BuyerPhoneEqualFold applies the EqualFold predicate on the "buyer_phone" field.
func BuyerPhoneEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldBuyerPhone, v))
}

// BuyerPhoneContainsFold applies the ContainsFold predicate on the "buyer_phone" field.
func BuyerPhoneContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldBuyerPhone, v))
}

// PaymentKeyEQ applies the EQ predicate on the "payment_key" field.
func PaymentKeyEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldPaymentKey, v))
}

// PaymentKeyNEQ applies the NEQ predicate on the "payment_key" field.
func PaymentKeyNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldPaymentKey, v))
}

// PaymentKeyIn applies the In predicate on the "payment_key" field.
func PaymentKeyIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldPaymentKey, vs...))
}

// PaymentKeyNotIn applies the NotIn predicate on the "payment_key" field.
func PaymentKeyNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldPaymentKey, vs...))
}

// PaymentKeyGT applies the GT predicate on the "payment_key" field.
func PaymentKeyGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldPaymentKey, v))
}

// PaymentKeyGTE applies the GTE predicate on the "payment_key" field.
func PaymentKeyGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldPaymentKey, v))
}

// PaymentKeyLT applies the LT predicate on the "payment_key" field.
func PaymentKeyLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldPaymentKey, v))
}

// PaymentKeyLTE applies the LTE predicate on the "payment_key" field.
func PaymentKeyLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldPaymentKey, v))
}

// PaymentKeyContains applies the Contains predicate on the "payment_key" field.
func PaymentKeyContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldPaymentKey, v))
}

// PaymentKeyHasPrefix applies the HasPrefix predicate on the "payment_key" field.
func PaymentKeyHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldPaymentKey, v))
}

// PaymentKeyHasSuffix applies the HasSuffix predicate on the "payment_key" field.
func PaymentKeyHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldPaymentKey, v))
}

// PaymentKeyIsNil applies the IsNil predicate on the "payment_key" field.
func PaymentKeyIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldPaymentKey))
}

// PaymentKeyNotNil applies the NotNil predicate on the "payment_key" field.
func PaymentKeyNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldPaymentKey))
}

// PaymentKeyEqualFold applies the EqualFold predicate on the "payment_key" field.
func PaymentKeyEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldPaymentKey, v))
}

// PaymentKeyContainsFold applies the ContainsFold predicate on the "payment_key" field.
func PaymentKeyContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldPaymentKey, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldOrderID))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldOrderID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.NotPredicates(p))
}
