// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/event"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/organization"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/payment"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/user"
	"github.com/google/uuid"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *EventUpdate) SetOrganizationID(v uuid.UUID) *EventUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableOrganizationID(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *EventUpdate) SetTitle(v string) *EventUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTitle(v *string) *EventUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdate) SetDescription(v string) *EventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDescription(v *string) *EventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EventUpdate) ClearDescription() *EventUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetLocation sets the "location" field.
func (_u *EventUpdate) SetLocation(v string) *EventUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *EventUpdate) SetNillableLocation(v *string) *EventUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *EventUpdate) ClearLocation() *EventUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetVenue sets the "venue" field.
func (_u *EventUpdate) SetVenue(v string) *EventUpdate {
	_u.mutation.SetVenue(v)
	return _u
}

// SetNillableVenue sets the "venue" field if the given value is not nil.
func (_u *EventUpdate) SetNillableVenue(v *string) *EventUpdate {
	if v != nil {
		_u.SetVenue(*v)
	}
	return _u
}

// ClearVenue clears the value of the "venue" field.
func (_u *EventUpdate) ClearVenue() *EventUpdate {
	_u.mutation.ClearVenue()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *EventUpdate) SetStartTime(v time.Time) *EventUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *EventUpdate) SetNillableStartTime(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *EventUpdate) SetEndTime(v time.Time) *EventUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *EventUpdate) SetNillableEndTime(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetTotalTickets sets the "total_tickets" field.
func (_u *EventUpdate) SetTotalTickets(v int) *EventUpdate {
	_u.mutation.ResetTotalTickets()
	_u.mutation.SetTotalTickets(v)
	return _u
}

// SetNillableTotalTickets sets the "total_tickets" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTotalTickets(v *int) *EventUpdate {
	if v != nil {
		_u.SetTotalTickets(*v)
	}
	return _u
}

// AddTotalTickets adds value to the "total_tickets" field.
func (_u *EventUpdate) AddTotalTickets(v int) *EventUpdate {
	_u.mutation.AddTotalTickets(v)
	return _u
}

// SetAvailableTickets sets the "available_tickets" field.
func (_u *EventUpdate) SetAvailableTickets(v int) *EventUpdate {
	_u.mutation.ResetAvailableTickets()
	_u.mutation.SetAvailableTickets(v)
	return _u
}

// SetNillableAvailableTickets sets the "available_tickets" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAvailableTickets(v *int) *EventUpdate {
	if v != nil {
		_u.SetAvailableTickets(*v)
	}
	return _u
}

// AddAvailableTickets adds value to the "available_tickets" field.
func (_u *EventUpdate) AddAvailableTickets(v int) *EventUpdate {
	_u.mutation.AddAvailableTickets(v)
	return _u
}

// SetParticipantCount sets the "participant_count" field.
func (_u *EventUpdate) SetParticipantCount(v int) *EventUpdate {
	_u.mutation.ResetParticipantCount()
	_u.mutation.SetParticipantCount(v)
	return _u
}

// SetNillableParticipantCount sets the "participant_count" field if the given value is not nil.
func (_u *EventUpdate) SetNillableParticipantCount(v *int) *EventUpdate {
	if v != nil {
		_u.SetParticipantCount(*v)
	}
	return _u
}

// AddParticipantCount adds value to the "participant_count" field.
func (_u *EventUpdate) AddParticipantCount(v int) *EventUpdate {
	_u.mutation.AddParticipantCount(v)
	return _u
}

// SetTicketPrice sets the "ticket_price" field.
func (_u *EventUpdate) SetTicketPrice(v float64) *EventUpdate {
	_u.mutation.ResetTicketPrice()
	_u.mutation.SetTicketPrice(v)
	return _u
}

// SetNillableTicketPrice sets the "ticket_price" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTicketPrice(v *float64) *EventUpdate {
	if v != nil {
		_u.SetTicketPrice(*v)
	}
	return _u
}

// AddTicketPrice adds value to the "ticket_price" field.
func (_u *EventUpdate) AddTicketPrice(v float64) *EventUpdate {
	_u.mutation.AddTicketPrice(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *EventUpdate) SetCurrency(v string) *EventUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *EventUpdate) SetNillableCurrency(v *string) *EventUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *EventUpdate) SetThumbnailURL(v string) *EventUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *EventUpdate) SetNillableThumbnailURL(v *string) *EventUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *EventUpdate) ClearThumbnailURL() *EventUpdate {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventUpdate) SetStatus(v event.Status) *EventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventUpdate) SetNillableStatus(v *event.Status) *EventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *EventUpdate) SetIsPublic(v bool) *EventUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *EventUpdate) SetNillableIsPublic(v *bool) *EventUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EventUpdate) SetCreatedBy(v uuid.UUID) *EventUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EventUpdate) SetNillableCreatedBy(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdate) SetUpdatedAt(v time.Time) *EventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *EventUpdate) SetOrganization(v *Organization) *EventUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *EventUpdate) SetCreatorID(id uuid.UUID) *EventUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *EventUpdate) SetCreator(v *User) *EventUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *EventUpdate) AddPaymentIDs(ids ...uuid.UUID) *EventUpdate {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *EventUpdate) AddPayments(v ...*Payment) *EventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *EventUpdate) ClearOrganization() *EventUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *EventUpdate) ClearCreator() *EventUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *EventUpdate) ClearPayments() *EventUpdate {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *EventUpdate) RemovePaymentIDs(ids ...uuid.UUID) *EventUpdate {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *EventUpdate) RemovePayments(v ...*Payment) *EventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := event.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalTickets(); ok {
		if err := event.TotalTicketsValidator(v); err != nil {
			return &ValidationError{Name: "total_tickets", err: fmt.Errorf(`ent: validator failed for field "Event.total_tickets": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvailableTickets(); ok {
		if err := event.AvailableTicketsValidator(v); err != nil {
			return &ValidationError{Name: "available_tickets", err: fmt.Errorf(`ent: validator failed for field "Event.available_tickets": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParticipantCount(); ok {
		if err := event.ParticipantCountValidator(v); err != nil {
			return &ValidationError{Name: "participant_count", err: fmt.Errorf(`ent: validator failed for field "Event.participant_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TicketPrice(); ok {
		if err := event.TicketPriceValidator(v); err != nil {
			return &ValidationError{Name: "ticket_price", err: fmt.Errorf(`ent: validator failed for field "Event.ticket_price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := event.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Event.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.organization"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.creator"`)
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(event.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(event.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(event.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Venue(); ok {
		_spec.SetField(event.FieldVenue, field.TypeString, value)
	}
	if _u.mutation.VenueCleared() {
		_spec.ClearField(event.FieldVenue, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(event.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(event.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalTickets(); ok {
		_spec.SetField(event.FieldTotalTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTickets(); ok {
		_spec.AddField(event.FieldTotalTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AvailableTickets(); ok {
		_spec.SetField(event.FieldAvailableTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvailableTickets(); ok {
		_spec.AddField(event.FieldAvailableTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParticipantCount(); ok {
		_spec.SetField(event.FieldParticipantCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParticipantCount(); ok {
		_spec.AddField(event.FieldParticipantCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TicketPrice(); ok {
		_spec.SetField(event.FieldTicketPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTicketPrice(); ok {
		_spec.AddField(event.FieldTicketPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(event.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(event.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(event.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(event.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.OrganizationTable,
			Columns: []string{event.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.OrganizationTable,
			Columns: []string{event.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.CreatorTable,
			Columns: []string{event.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.CreatorTable,
			Columns: []string{event.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetOrganizationID sets the "organization_id" field.
func (_u *EventUpdateOne) SetOrganizationID(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *EventUpdateOne) SetTitle(v string) *EventUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTitle(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdateOne) SetDescription(v string) *EventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDescription(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EventUpdateOne) ClearDescription() *EventUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetLocation sets the "location" field.
func (_u *EventUpdateOne) SetLocation(v string) *EventUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableLocation(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *EventUpdateOne) ClearLocation() *EventUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetVenue sets the "venue" field.
func (_u *EventUpdateOne) SetVenue(v string) *EventUpdateOne {
	_u.mutation.SetVenue(v)
	return _u
}

// SetNillableVenue sets the "venue" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableVenue(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetVenue(*v)
	}
	return _u
}

// ClearVenue clears the value of the "venue" field.
func (_u *EventUpdateOne) ClearVenue() *EventUpdateOne {
	_u.mutation.ClearVenue()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *EventUpdateOne) SetStartTime(v time.Time) *EventUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableStartTime(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *EventUpdateOne) SetEndTime(v time.Time) *EventUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableEndTime(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetTotalTickets sets the "total_tickets" field.
func (_u *EventUpdateOne) SetTotalTickets(v int) *EventUpdateOne {
	_u.mutation.ResetTotalTickets()
	_u.mutation.SetTotalTickets(v)
	return _u
}

// SetNillableTotalTickets sets the "total_tickets" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTotalTickets(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetTotalTickets(*v)
	}
	return _u
}

// AddTotalTickets adds value to the "total_tickets" field.
func (_u *EventUpdateOne) AddTotalTickets(v int) *EventUpdateOne {
	_u.mutation.AddTotalTickets(v)
	return _u
}

// SetAvailableTickets sets the "available_tickets" field.
func (_u *EventUpdateOne) SetAvailableTickets(v int) *EventUpdateOne {
	_u.mutation.ResetAvailableTickets()
	_u.mutation.SetAvailableTickets(v)
	return _u
}

// SetNillableAvailableTickets sets the "available_tickets" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAvailableTickets(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetAvailableTickets(*v)
	}
	return _u
}

// AddAvailableTickets adds value to the "available_tickets" field.
func (_u *EventUpdateOne) AddAvailableTickets(v int) *EventUpdateOne {
	_u.mutation.AddAvailableTickets(v)
	return _u
}

// SetParticipantCount sets the "participant_count" field.
func (_u *EventUpdateOne) SetParticipantCount(v int) *EventUpdateOne {
	_u.mutation.ResetParticipantCount()
	_u.mutation.SetParticipantCount(v)
	return _u
}

// SetNillableParticipantCount sets the "participant_count" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableParticipantCount(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetParticipantCount(*v)
	}
	return _u
}

// AddParticipantCount adds value to the "participant_count" field.
func (_u *EventUpdateOne) AddParticipantCount(v int) *EventUpdateOne {
	_u.mutation.AddParticipantCount(v)
	return _u
}

// SetTicketPrice sets the "ticket_price" field.
func (_u *EventUpdateOne) SetTicketPrice(v float64) *EventUpdateOne {
	_u.mutation.ResetTicketPrice()
	_u.mutation.SetTicketPrice(v)
	return _u
}

// SetNillableTicketPrice sets the "ticket_price" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTicketPrice(v *float64) *EventUpdateOne {
	if v != nil {
		_u.SetTicketPrice(*v)
	}
	return _u
}

// AddTicketPrice adds value to the "ticket_price" field.
func (_u *EventUpdateOne) AddTicketPrice(v float64) *EventUpdateOne {
	_u.mutation.AddTicketPrice(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *EventUpdateOne) SetCurrency(v string) *EventUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableCurrency(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *EventUpdateOne) SetThumbnailURL(v string) *EventUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableThumbnailURL(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *EventUpdateOne) ClearThumbnailURL() *EventUpdateOne {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventUpdateOne) SetStatus(v event.Status) *EventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableStatus(v *event.Status) *EventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *EventUpdateOne) SetIsPublic(v bool) *EventUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableIsPublic(v *bool) *EventUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EventUpdateOne) SetCreatedBy(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdateOne) SetUpdatedAt(v time.Time) *EventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *EventUpdateOne) SetOrganization(v *Organization) *EventUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *EventUpdateOne) SetCreatorID(id uuid.UUID) *EventUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *EventUpdateOne) SetCreator(v *User) *EventUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *EventUpdateOne) AddPaymentIDs(ids ...uuid.UUID) *EventUpdateOne {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *EventUpdateOne) AddPayments(v ...*Payment) *EventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *EventUpdateOne) ClearOrganization() *EventUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *EventUpdateOne) ClearCreator() *EventUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *EventUpdateOne) ClearPayments() *EventUpdateOne {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *EventUpdateOne) RemovePaymentIDs(ids ...uuid.UUID) *EventUpdateOne {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *EventUpdateOne) RemovePayments(v ...*Payment) *EventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := event.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalTickets(); ok {
		if err := event.TotalTicketsValidator(v); err != nil {
			return &ValidationError{Name: "total_tickets", err: fmt.Errorf(`ent: validator failed for field "Event.total_tickets": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvailableTickets(); ok {
		if err := event.AvailableTicketsValidator(v); err != nil {
			return &ValidationError{Name: "available_tickets", err: fmt.Errorf(`ent: validator failed for field "Event.available_tickets": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParticipantCount(); ok {
		if err := event.ParticipantCountValidator(v); err != nil {
			return &ValidationError{Name: "participant_count", err: fmt.Errorf(`ent: validator failed for field "Event.participant_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TicketPrice(); ok {
		if err := event.TicketPriceValidator(v); err != nil {
			return &ValidationError{Name: "ticket_price", err: fmt.Errorf(`ent: validator failed for field "Event.ticket_price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := event.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Event.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.organization"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Event.creator"`)
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(event.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(event.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(event.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Venue(); ok {
		_spec.SetField(event.FieldVenue, field.TypeString, value)
	}
	if _u.mutation.VenueCleared() {
		_spec.ClearField(event.FieldVenue, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(event.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(event.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalTickets(); ok {
		_spec.SetField(event.FieldTotalTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTickets(); ok {
		_spec.AddField(event.FieldTotalTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AvailableTickets(); ok {
		_spec.SetField(event.FieldAvailableTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvailableTickets(); ok {
		_spec.AddField(event.FieldAvailableTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParticipantCount(); ok {
		_spec.SetField(event.FieldParticipantCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParticipantCount(); ok {
		_spec.AddField(event.FieldParticipantCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TicketPrice(); ok {
		_spec.SetField(event.FieldTicketPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTicketPrice(); ok {
		_spec.AddField(event.FieldTicketPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(event.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(event.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(event.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(event.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.OrganizationTable,
			Columns: []string{event.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.OrganizationTable,
			Columns: []string{event.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.CreatorTable,
			Columns: []string{event.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.CreatorTable,
			Columns: []string{event.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
