// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/event"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/organization"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/payment"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/user"
	"github.com/google/uuid"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *EventCreate) SetOrganizationID(v uuid.UUID) *EventCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *EventCreate) SetTitle(v string) *EventCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *EventCreate) SetDescription(v string) *EventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EventCreate) SetNillableDescription(v *string) *EventCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *EventCreate) SetLocation(v string) *EventCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *EventCreate) SetNillableLocation(v *string) *EventCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetVenue sets the "venue" field.
func (_c *EventCreate) SetVenue(v string) *EventCreate {
	_c.mutation.SetVenue(v)
	return _c
}

// SetNillableVenue sets the "venue" field if the given value is not nil.
func (_c *EventCreate) SetNillableVenue(v *string) *EventCreate {
	if v != nil {
		_c.SetVenue(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *EventCreate) SetStartTime(v time.Time) *EventCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *EventCreate) SetEndTime(v time.Time) *EventCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetTotalTickets sets the "total_tickets" field.
func (_c *EventCreate) SetTotalTickets(v int) *EventCreate {
	_c.mutation.SetTotalTickets(v)
	return _c
}

// SetNillableTotalTickets sets the "total_tickets" field if the given value is not nil.
func (_c *EventCreate) SetNillableTotalTickets(v *int) *EventCreate {
	if v != nil {
		_c.SetTotalTickets(*v)
	}
	return _c
}

// SetAvailableTickets sets the "available_tickets" field.
func (_c *EventCreate) SetAvailableTickets(v int) *EventCreate {
	_c.mutation.SetAvailableTickets(v)
	return _c
}

// SetNillableAvailableTickets sets the "available_tickets" field if the given value is not nil.
func (_c *EventCreate) SetNillableAvailableTickets(v *int) *EventCreate {
	if v != nil {
		_c.SetAvailableTickets(*v)
	}
	return _c
}

// SetTicketPrice sets the "ticket_price" field.
func (_c *EventCreate) SetTicketPrice(v float64) *EventCreate {
	_c.mutation.SetTicketPrice(v)
	return _c
}

// SetNillableTicketPrice sets the "ticket_price" field if the given value is not nil.
func (_c *EventCreate) SetNillableTicketPrice(v *float64) *EventCreate {
	if v != nil {
		_c.SetTicketPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *EventCreate) SetCurrency(v string) *EventCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *EventCreate) SetNillableCurrency(v *string) *EventCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *EventCreate) SetThumbnailURL(v string) *EventCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *EventCreate) SetNillableThumbnailURL(v *string) *EventCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EventCreate) SetStatus(v event.Status) *EventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventCreate) SetNillableStatus(v *event.Status) *EventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *EventCreate) SetIsPublic(v bool) *EventCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *EventCreate) SetNillableIsPublic(v *bool) *EventCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EventCreate) SetCreatedBy(v uuid.UUID) *EventCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventCreate) SetCreatedAt(v time.Time) *EventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventCreate) SetUpdatedAt(v time.Time) *EventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v uuid.UUID) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventCreate) SetNillableID(v *uuid.UUID) *EventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *EventCreate) SetOrganization(v *Organization) *EventCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *EventCreate) SetCreatorID(id uuid.UUID) *EventCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *EventCreate) SetCreator(v *User) *EventCreate {
	return _c.SetCreatorID(v.ID)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_c *EventCreate) AddPaymentIDs(ids ...uuid.UUID) *EventCreate {
	_c.mutation.AddPaymentIDs(ids...)
	return _c
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_c *EventCreate) AddPayments(v ...*Payment) *EventCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPaymentIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.TotalTickets(); !ok {
		v := event.DefaultTotalTickets
		_c.mutation.SetTotalTickets(v)
	}
	if _, ok := _c.mutation.AvailableTickets(); !ok {
		v := event.DefaultAvailableTickets
		_c.mutation.SetAvailableTickets(v)
	}
	if _, ok := _c.mutation.TicketPrice(); !ok {
		v := event.DefaultTicketPrice
		_c.mutation.SetTicketPrice(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := event.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := event.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := event.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := event.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := event.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := event.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "Event.organization_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Event.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Event.start_time"`)}
	}
	if _, ok := _c.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "Event.end_time"`)}
	}
	if _, ok := _c.mutation.TotalTickets(); !ok {
		return &ValidationError{Name: "total_tickets", err: errors.New(`ent: missing required field "Event.total_tickets"`)}
	}
	if v, ok := _c.mutation.TotalTickets(); ok {
		if err := event.TotalTicketsValidator(v); err != nil {
			return &ValidationError{Name: "total_tickets", err: fmt.Errorf(`ent: validator failed for field "Event.total_tickets": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AvailableTickets(); !ok {
		return &ValidationError{Name: "available_tickets", err: errors.New(`ent: missing required field "Event.available_tickets"`)}
	}
	if v, ok := _c.mutation.AvailableTickets(); ok {
		if err := event.AvailableTicketsValidator(v); err != nil {
			return &ValidationError{Name: "available_tickets", err: fmt.Errorf(`ent: validator failed for field "Event.available_tickets": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TicketPrice(); !ok {
		return &ValidationError{Name: "ticket_price", err: errors.New(`ent: missing required field "Event.ticket_price"`)}
	}
	if v, ok := _c.mutation.TicketPrice(); ok {
		if err := event.TicketPriceValidator(v); err != nil {
			return &ValidationError{Name: "ticket_price", err: fmt.Errorf(`ent: validator failed for field "Event.ticket_price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Event.currency"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Event.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := event.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Event.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Event.is_public"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Event.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Event.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Event.updated_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "Event.organization"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Event.creator"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(event.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Venue(); ok {
		_spec.SetField(event.FieldVenue, field.TypeString, value)
		_node.Venue = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(event.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(event.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.TotalTickets(); ok {
		_spec.SetField(event.FieldTotalTickets, field.TypeInt, value)
		_node.TotalTickets = value
	}
	if value, ok := _c.mutation.AvailableTickets(); ok {
		_spec.SetField(event.FieldAvailableTickets, field.TypeInt, value)
		_node.AvailableTickets = value
	}
	if value, ok := _c.mutation.TicketPrice(); ok {
		_spec.SetField(event.FieldTicketPrice, field.TypeFloat64, value)
		_node.TicketPrice = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(event.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(event.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(event.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.OrganizationTable,
			Columns: []string{event.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.CreatorTable,
			Columns: []string{event.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.PaymentsTable,
			Columns: []string{event.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
