// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/event"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/payment"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/user"
	"github.com/google/uuid"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	mutation *PaymentMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *PaymentCreate) SetEventID(v uuid.UUID) *PaymentCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentCreate) SetUserID(v uuid.UUID) *PaymentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableUserID(v *uuid.UUID) *PaymentCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetEventTitle sets the "event_title" field.
func (_c *PaymentCreate) SetEventTitle(v string) *PaymentCreate {
	_c.mutation.SetEventTitle(v)
	return _c
}

// SetTicketQuantity sets the "ticket_quantity" field.
func (_c *PaymentCreate) SetTicketQuantity(v int) *PaymentCreate {
	_c.mutation.SetTicketQuantity(v)
	return _c
}

// SetTotalPrice sets the "total_price" field.
func (_c *PaymentCreate) SetTotalPrice(v float64) *PaymentCreate {
	_c.mutation.SetTotalPrice(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentCreate) SetCurrency(v string) *PaymentCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableCurrency(v *string) *PaymentCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetBuyerName sets the "buyer_name" field.
func (_c *PaymentCreate) SetBuyerName(v string) *PaymentCreate {
	_c.mutation.SetBuyerName(v)
	return _c
}

// SetBuyerEmail sets the "buyer_email" field.
func (_c *PaymentCreate) SetBuyerEmail(v string) *PaymentCreate {
	_c.mutation.SetBuyerEmail(v)
	return _c
}

// SetBuyerPhone sets the "buyer_phone" field.
func (_c *PaymentCreate) SetBuyerPhone(v string) *PaymentCreate {
	_c.mutation.SetBuyerPhone(v)
	return _c
}

// SetPaymentKey sets the "payment_key" field.
func (_c *PaymentCreate) SetPaymentKey(v string) *PaymentCreate {
	_c.mutation.SetPaymentKey(v)
	return _c
}

// SetNillablePaymentKey sets the "payment_key" field if the given value is not nil.
func (_c *PaymentCreate) SetNillablePaymentKey(v *string) *PaymentCreate {
	if v != nil {
		_c.SetPaymentKey(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *PaymentCreate) SetOrderID(v string) *PaymentCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableOrderID(v *string) *PaymentCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentCreate) SetStatus(v payment.Status) *PaymentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableStatus(v *payment.Status) *PaymentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentCreate) SetCreatedAt(v time.Time) *PaymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableCreatedAt(v *time.Time) *PaymentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentCreate) SetUpdatedAt(v time.Time) *PaymentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableUpdatedAt(v *time.Time) *PaymentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentCreate) SetID(v uuid.UUID) *PaymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableID(v *uuid.UUID) *PaymentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *PaymentCreate) SetEvent(v *Event) *PaymentCreate {
	return _c.SetEventID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentCreate) SetUser(v *User) *PaymentCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_c *PaymentCreate) Mutation() *PaymentMutation {
	return _c.mutation
}

// Save creates the Payment in the database.
func (_c *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := payment.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := payment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := payment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := payment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := payment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "Payment.event_id"`)}
	}
	if _, ok := _c.mutation.EventTitle(); !ok {
		return &ValidationError{Name: "event_title", err: errors.New(`ent: missing required field "Payment.event_title"`)}
	}
	if v, ok := _c.mutation.EventTitle(); ok {
		if err := payment.EventTitleValidator(v); err != nil {
			return &ValidationError{Name: "event_title", err: fmt.Errorf(`ent: validator failed for field "Payment.event_title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TicketQuantity(); !ok {
		return &ValidationError{Name: "ticket_quantity", err: errors.New(`ent: missing required field "Payment.ticket_quantity"`)}
	}
	if v, ok := _c.mutation.TicketQuantity(); ok {
		if err := payment.TicketQuantityValidator(v); err != nil {
			return &ValidationError{Name: "ticket_quantity", err: fmt.Errorf(`ent: validator failed for field "Payment.ticket_quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		return &ValidationError{Name: "total_price", err: errors.New(`ent: missing required field "Payment.total_price"`)}
	}
	if v, ok := _c.mutation.TotalPrice(); ok {
		if err := payment.TotalPriceValidator(v); err != nil {
			return &ValidationError{Name: "total_price", err: fmt.Errorf(`ent: validator failed for field "Payment.total_price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Payment.currency"`)}
	}
	if _, ok := _c.mutation.BuyerName(); !ok {
		return &ValidationError{Name: "buyer_name", err: errors.New(`ent: missing required field "Payment.buyer_name"`)}
	}
	if v, ok := _c.mutation.BuyerName(); ok {
		if err := payment.BuyerNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_name", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerEmail(); !ok {
		return &ValidationError{Name: "buyer_email", err: errors.New(`ent: missing required field "Payment.buyer_email"`)}
	}
	if v, ok := _c.mutation.BuyerEmail(); ok {
		if err := payment.BuyerEmailValidator(v); err != nil {
			return &ValidationError{Name: "buyer_email", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerPhone(); !ok {
		return &ValidationError{Name: "buyer_phone", err: errors.New(`ent: missing required field "Payment.buyer_phone"`)}
	}
	if v, ok := _c.mutation.BuyerPhone(); ok {
		if err := payment.BuyerPhoneValidator(v); err != nil {
			return &ValidationError{Name: "buyer_phone", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Payment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Payment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Payment.updated_at"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "Payment.event"`)}
	}
	return nil
}

func (_c *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentCreate) createSpec() (*Payment, *sqlgraph.CreateSpec) {
	var (
		_node = &Payment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payment.Table, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EventTitle(); ok {
		_spec.SetField(payment.FieldEventTitle, field.TypeString, value)
		_node.EventTitle = value
	}
	if value, ok := _c.mutation.TicketQuantity(); ok {
		_spec.SetField(payment.FieldTicketQuantity, field.TypeInt, value)
		_node.TicketQuantity = value
	}
	if value, ok := _c.mutation.TotalPrice(); ok {
		_spec.SetField(payment.FieldTotalPrice, field.TypeFloat64, value)
		_node.TotalPrice = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.BuyerName(); ok {
		_spec.SetField(payment.FieldBuyerName, field.TypeString, value)
		_node.BuyerName = value
	}
	if value, ok := _c.mutation.BuyerEmail(); ok {
		_spec.SetField(payment.FieldBuyerEmail, field.TypeString, value)
		_node.BuyerEmail = value
	}
	if value, ok := _c.mutation.BuyerPhone(); ok {
		_spec.SetField(payment.FieldBuyerPhone, field.TypeString, value)
		_node.BuyerPhone = value
	}
	if value, ok := _c.mutation.PaymentKey(); ok {
		_spec.SetField(payment.FieldPaymentKey, field.TypeString, value)
		_node.PaymentKey = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(payment.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(payment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.EventTable,
			Columns: []string{payment.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentCreateBulk is the builder for creating many Payment entities in bulk.
type PaymentCreateBulk struct {
	config
	err      error
	builders []*PaymentCreate
}

// Save creates the Payment entities in the database.
func (_c *PaymentCreateBulk) Save(ctx context.Context) ([]*Payment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Payment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentCreateBulk) SaveX(ctx context.Context) []*Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
