// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/event"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/payment"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/ticketly-backend/lib/ent/user"
	"github.com/google/uuid"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *PaymentUpdate) SetEventID(v uuid.UUID) *PaymentUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableEventID(v *uuid.UUID) *PaymentUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentUpdate) SetUserID(v uuid.UUID) *PaymentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableUserID(v *uuid.UUID) *PaymentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PaymentUpdate) ClearUserID() *PaymentUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetEventTitle sets the "event_title" field.
func (_u *PaymentUpdate) SetEventTitle(v string) *PaymentUpdate {
	_u.mutation.SetEventTitle(v)
	return _u
}

// SetNillableEventTitle sets the "event_title" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableEventTitle(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetEventTitle(*v)
	}
	return _u
}

// SetTicketQuantity sets the "ticket_quantity" field.
func (_u *PaymentUpdate) SetTicketQuantity(v int) *PaymentUpdate {
	_u.mutation.ResetTicketQuantity()
	_u.mutation.SetTicketQuantity(v)
	return _u
}

// SetNillableTicketQuantity sets the "ticket_quantity" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableTicketQuantity(v *int) *PaymentUpdate {
	if v != nil {
		_u.SetTicketQuantity(*v)
	}
	return _u
}

// AddTicketQuantity adds value to the "ticket_quantity" field.
func (_u *PaymentUpdate) AddTicketQuantity(v int) *PaymentUpdate {
	_u.mutation.AddTicketQuantity(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *PaymentUpdate) SetTotalPrice(v float64) *PaymentUpdate {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableTotalPrice(v *float64) *PaymentUpdate {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *PaymentUpdate) AddTotalPrice(v float64) *PaymentUpdate {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentUpdate) SetCurrency(v string) *PaymentUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableCurrency(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetBuyerName sets the "buyer_name" field.
func (_u *PaymentUpdate) SetBuyerName(v string) *PaymentUpdate {
	_u.mutation.SetBuyerName(v)
	return _u
}

// SetNillableBuyerName sets the "buyer_name" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableBuyerName(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetBuyerName(*v)
	}
	return _u
}

// SetBuyerEmail sets the "buyer_email" field.
func (_u *PaymentUpdate) SetBuyerEmail(v string) *PaymentUpdate {
	_u.mutation.SetBuyerEmail(v)
	return _u
}

// SetNillableBuyerEmail sets the "buyer_email" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableBuyerEmail(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetBuyerEmail(*v)
	}
	return _u
}

// SetBuyerPhone sets the "buyer_phone" field.
func (_u *PaymentUpdate) SetBuyerPhone(v string) *PaymentUpdate {
	_u.mutation.SetBuyerPhone(v)
	return _u
}

// SetNillableBuyerPhone sets the "buyer_phone" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableBuyerPhone(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetBuyerPhone(*v)
	}
	return _u
}

// SetPaymentKey sets the "payment_key" field.
func (_u *PaymentUpdate) SetPaymentKey(v string) *PaymentUpdate {
	_u.mutation.SetPaymentKey(v)
	return _u
}

// SetNillablePaymentKey sets the "payment_key" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePaymentKey(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetPaymentKey(*v)
	}
	return _u
}

// ClearPaymentKey clears the value of the "payment_key" field.
func (_u *PaymentUpdate) ClearPaymentKey() *PaymentUpdate {
	_u.mutation.ClearPaymentKey()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *PaymentUpdate) SetOrderID(v string) *PaymentUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableOrderID(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *PaymentUpdate) ClearOrderID() *PaymentUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdate) SetStatus(v payment.Status) *PaymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableStatus(v *payment.Status) *PaymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdate) SetUpdatedAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PaymentUpdate) SetEvent(v *Event) *PaymentUpdate {
	return _u.SetEventID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentUpdate) SetUser(v *User) *PaymentUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PaymentUpdate) ClearEvent() *PaymentUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentUpdate) ClearUser() *PaymentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if v, ok := _u.mutation.EventTitle(); ok {
		if err := payment.EventTitleValidator(v); err != nil {
			return &ValidationError{Name: "event_title", err: fmt.Errorf(`ent: validator failed for field "Payment.event_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TicketQuantity(); ok {
		if err := payment.TicketQuantityValidator(v); err != nil {
			return &ValidationError{Name: "ticket_quantity", err: fmt.Errorf(`ent: validator failed for field "Payment.ticket_quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalPrice(); ok {
		if err := payment.TotalPriceValidator(v); err != nil {
			return &ValidationError{Name: "total_price", err: fmt.Errorf(`ent: validator failed for field "Payment.total_price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerName(); ok {
		if err := payment.BuyerNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_name", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerEmail(); ok {
		if err := payment.BuyerEmailValidator(v); err != nil {
			return &ValidationError{Name: "buyer_email", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerPhone(); ok {
		if err := payment.BuyerPhoneValidator(v); err != nil {
			return &ValidationError{Name: "buyer_phone", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.event"`)
	}
	return nil
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventTitle(); ok {
		_spec.SetField(payment.FieldEventTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TicketQuantity(); ok {
		_spec.SetField(payment.FieldTicketQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTicketQuantity(); ok {
		_spec.AddField(payment.FieldTicketQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(payment.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(payment.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerName(); ok {
		_spec.SetField(payment.FieldBuyerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerEmail(); ok {
		_spec.SetField(payment.FieldBuyerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerPhone(); ok {
		_spec.SetField(payment.FieldBuyerPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentKey(); ok {
		_spec.SetField(payment.FieldPaymentKey, field.TypeString, value)
	}
	if _u.mutation.PaymentKeyCleared() {
		_spec.ClearField(payment.FieldPaymentKey, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(payment.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(payment.FieldOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.EventTable,
			Columns: []string{payment.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.EventTable,
			Columns: []string{payment.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetEventID sets the "event_id" field.
func (_u *PaymentUpdateOne) SetEventID(v uuid.UUID) *PaymentUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableEventID(v *uuid.UUID) *PaymentUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentUpdateOne) SetUserID(v uuid.UUID) *PaymentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableUserID(v *uuid.UUID) *PaymentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PaymentUpdateOne) ClearUserID() *PaymentUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetEventTitle sets the "event_title" field.
func (_u *PaymentUpdateOne) SetEventTitle(v string) *PaymentUpdateOne {
	_u.mutation.SetEventTitle(v)
	return _u
}

// SetNillableEventTitle sets the "event_title" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableEventTitle(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetEventTitle(*v)
	}
	return _u
}

// SetTicketQuantity sets the "ticket_quantity" field.
func (_u *PaymentUpdateOne) SetTicketQuantity(v int) *PaymentUpdateOne {
	_u.mutation.ResetTicketQuantity()
	_u.mutation.SetTicketQuantity(v)
	return _u
}

// SetNillableTicketQuantity sets the "ticket_quantity" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableTicketQuantity(v *int) *PaymentUpdateOne {
	if v != nil {
		_u.SetTicketQuantity(*v)
	}
	return _u
}

// AddTicketQuantity adds value to the "ticket_quantity" field.
func (_u *PaymentUpdateOne) AddTicketQuantity(v int) *PaymentUpdateOne {
	_u.mutation.AddTicketQuantity(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *PaymentUpdateOne) SetTotalPrice(v float64) *PaymentUpdateOne {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableTotalPrice(v *float64) *PaymentUpdateOne {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *PaymentUpdateOne) AddTotalPrice(v float64) *PaymentUpdateOne {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentUpdateOne) SetCurrency(v string) *PaymentUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableCurrency(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetBuyerName sets the "buyer_name" field.
func (_u *PaymentUpdateOne) SetBuyerName(v string) *PaymentUpdateOne {
	_u.mutation.SetBuyerName(v)
	return _u
}

// SetNillableBuyerName sets the "buyer_name" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableBuyerName(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetBuyerName(*v)
	}
	return _u
}

// SetBuyerEmail sets the "buyer_email" field.
func (_u *PaymentUpdateOne) SetBuyerEmail(v string) *PaymentUpdateOne {
	_u.mutation.SetBuyerEmail(v)
	return _u
}

// SetNillableBuyerEmail sets the "buyer_email" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableBuyerEmail(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetBuyerEmail(*v)
	}
	return _u
}

// SetBuyerPhone sets the "buyer_phone" field.
func (_u *PaymentUpdateOne) SetBuyerPhone(v string) *PaymentUpdateOne {
	_u.mutation.SetBuyerPhone(v)
	return _u
}

// SetNillableBuyerPhone sets the "buyer_phone" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableBuyerPhone(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetBuyerPhone(*v)
	}
	return _u
}

// SetPaymentKey sets the "payment_key" field.
func (_u *PaymentUpdateOne) SetPaymentKey(v string) *PaymentUpdateOne {
	_u.mutation.SetPaymentKey(v)
	return _u
}

// SetNillablePaymentKey sets the "payment_key" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePaymentKey(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetPaymentKey(*v)
	}
	return _u
}

// ClearPaymentKey clears the value of the "payment_key" field.
func (_u *PaymentUpdateOne) ClearPaymentKey() *PaymentUpdateOne {
	_u.mutation.ClearPaymentKey()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *PaymentUpdateOne) SetOrderID(v string) *PaymentUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableOrderID(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *PaymentUpdateOne) ClearOrderID() *PaymentUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdateOne) SetStatus(v payment.Status) *PaymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableStatus(v *payment.Status) *PaymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdateOne) SetUpdatedAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PaymentUpdateOne) SetEvent(v *Event) *PaymentUpdateOne {
	return _u.SetEventID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentUpdateOne) SetUser(v *User) *PaymentUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PaymentUpdateOne) ClearEvent() *PaymentUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentUpdateOne) ClearUser() *PaymentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if v, ok := _u.mutation.EventTitle(); ok {
		if err := payment.EventTitleValidator(v); err != nil {
			return &ValidationError{Name: "event_title", err: fmt.Errorf(`ent: validator failed for field "Payment.event_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TicketQuantity(); ok {
		if err := payment.TicketQuantityValidator(v); err != nil {
			return &ValidationError{Name: "ticket_quantity", err: fmt.Errorf(`ent: validator failed for field "Payment.ticket_quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalPrice(); ok {
		if err := payment.TotalPriceValidator(v); err != nil {
			return &ValidationError{Name: "total_price", err: fmt.Errorf(`ent: validator failed for field "Payment.total_price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerName(); ok {
		if err := payment.BuyerNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_name", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerEmail(); ok {
		if err := payment.BuyerEmailValidator(v); err != nil {
			return &ValidationError{Name: "buyer_email", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerPhone(); ok {
		if err := payment.BuyerPhoneValidator(v); err != nil {
			return &ValidationError{Name: "buyer_phone", err: fmt.Errorf(`ent: validator failed for field "Payment.buyer_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.event"`)
	}
	return nil
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventTitle(); ok {
		_spec.SetField(payment.FieldEventTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TicketQuantity(); ok {
		_spec.SetField(payment.FieldTicketQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTicketQuantity(); ok {
		_spec.AddField(payment.FieldTicketQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(payment.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(payment.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerName(); ok {
		_spec.SetField(payment.FieldBuyerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerEmail(); ok {
		_spec.SetField(payment.FieldBuyerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerPhone(); ok {
		_spec.SetField(payment.FieldBuyerPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentKey(); ok {
		_spec.SetField(payment.FieldPaymentKey, field.TypeString, value)
	}
	if _u.mutation.PaymentKeyCleared() {
		_spec.ClearField(payment.FieldPaymentKey, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(payment.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(payment.FieldOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.EventTable,
			Columns: []string{payment.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.EventTable,
			Columns: []string{payment.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
